id: P006878
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24220
  title: དགའ་ལྡན་ཤར་རྩེའི་ཆོས་སྤྱོད་མཛད་རིམ་ངོ་མཚར་བསྟན་པའི་མཛེས་རྒྱན་ཉིན་བྱེད་སྣང་བའི་ཡང་གསལ།
  author: ''
  volumes:
    374cb39c5c274effa0731835fadc132d:
      image_group_id: I1KG24300
      title: ''
      volume_number: 1
      total_pages: 0
    d979228ee4744722992869d89bb455e2:
      image_group_id: I1KG24301
      title: ''
      volume_number: 2
      total_pages: 904
      base_file: v001.txt
    004b8d301e5149c68ac29084f8f7ebca:
      image_group_id: I1KG24302
      title: ''
      volume_number: 3
      total_pages: 798
      base_file: v002.txt
